### ISSUE TITLE
More configure to the placeholders

### ISSUE THREAD

**Issue by redbug312** [lucax88x/CodeAceJumper#10]
though the color configure makes visibility great, I think the readability can be improved from:
1. font-weight settings
2. font-family settings, for it fallbacks to some serif font when there's no Consolas on my computer
3. capital letters settings, as the demo in the marketplace page

**Comment by lucax88x** [comment]
Sure, I can do this.

You need to give me one week, because atm I'm at the hospital as my wife gave me my first daughter :)

**Comment by redbug312** [comment]
Thanks, and Congratulations!

**Comment by lucax88x** [comment]
unfortunately, as this is a SVG, it's hard to calculate how the text is large with a different font-size, (at least for what I'm aware of), so I'll just give users possibility to configure everything.

as you can see in the 1.1.3 readme, I've added these configurations:

* `aceJump.placeholder.width`: placeholder width; defaults to 12
* `aceJump.placeholder.height`: placeholder height; defaults to 14
* `aceJump.placeholder.fontSize`: placeholder font size; defaults to 14
* `aceJump.placeholder.textPosX`: placeholder text X position; defaults to 2
* `aceJump.placeholder.textPosY`: placeholder text Y position; defaults to 12
* `aceJump.placeholder.fontWeight`: placeholder font weight; defaults to normal
* `aceJump.placeholder.fontFamily`: placeholder font family; defaults to Consolas
* `aceJump.placeholder.upperCase`: placeholder font to uppercase; defaults to false

new version is released as 1.1.3

let me know if this satisfies you!
