### ISSUE TITLE
Doesn't work with October update

### ISSUE THREAD

**Issue by BovineEnthusiast** [lucax88x/CodeAceJumper#107]
Looks like the latest vscode update broke the text overlay. When I try to jump to `s` this is what I see:

![Screen Shot 2019-11-09 at 9 04 38 AM](https://user-images.githubusercontent.com/8148243/68532265-13fca900-02d0-11ea-8ae1-df4feaf4428a.png)

**Comment by lucax88x** [comment]
Ouch, damn. I'll take a look on monday.

**Comment by lucax88x** [comment]
I just updated vscode, I have version 1.40 and the extension is still working fine for me. which version do you have?

**Comment by BovineEnthusiast** [comment]
VSCode 1.40.0
AceJumper: 2.1.6

Hmm... I haven't changed anything else recently 🤔 I tried reinstalling the extension and still have the issue. Might be a local thing. I'll comment again when I get a chance to restart my computer in case that fixes it.

**Comment by lucax88x** [comment]
Can you try disabling other extensions? I have suspects on the theme..

**Comment by BovineEnthusiast** [comment]
Disabling all extensions (including themes): No
Restarting computer: No

HOWEVER, I reset all the extension settings and that fixed it. The weird thing is that I haven't touched those settings in forever. Looks like changing the `Placeholder:Background Color` to an invalid property will replicate the screenshot above. I should have taken a screenshot before resetting all the settings.

Anyways, thanks for the help!
