### ISSUE TITLE
Selection mode doesn't select last character

### ISSUE THREAD

**Issue by icher** [lucax88x/CodeAceJumper#108]
Hi, it's already mentioned here #31 , but I guess you don't figured out what exactly OP wanted.

There's a gif:

![Peek 2019-11-10 15-02](https://user-images.githubusercontent.com/8604717/68541585-80100780-03cb-11ea-8251-2ebb8fc2194f.gif)

I'm triggered ace jump selection mode then type "," to select all characters including ",". But "," doesn't selected. Actually it's not about "," it's any character where you actually jumping in selection mode doesn't selected.

**Comment by lucax88x** [comment]
Well, I understood! Will fix tomorrow. Thanks!

**Comment by lucax88x** [comment]
Released with 2.1.7
