### ISSUE TITLE
It doesn't work with VIM extension

### ISSUE THREAD

**Issue by jakub-wojciech** [lucax88x/CodeAceJumper#11]
Hi,
It looks like this extension doesn't work at all with vim extension for VSC (https://marketplace.visualstudio.com/items?itemName=vscodevim.vim)

Any chance to fix that?

**Comment by lucax88x** [comment]
Just tried it, yeah this does not work at all with the mentioned extension!

I'll have a look during the week, I promise you.

**Comment by lucax88x** [comment]
sorry.. that's a problem I cannot solve actually.

You can see a similar issue there.

https://github.com/Microsoft/vscode/issues/13441

We we have to wait feedbacks on this.

**Comment by thesimonho** [comment]
this seems to also be a problem with vim installed but disabled. any reason why vim still takes over the keybinding even if it is disabled?

**Comment by lucax88x** [comment]
This is weird, did you reload vscode after disabling the vim extensions? Or maybe you have another extensions using this keybinding?

**Comment by thesimonho** [comment]
ah seems to work now. I probably just didnt reload/restart code after trying the last time

**Comment by matklad** [comment]
@lucax88x see 
https://github.com/metaseed/metaGo/blob/0422537c5750c50283e0950d986c89221d076291/src/metajumper/inline-input.ts#L36 for a nice workaround!

**Comment by lucax88x** [comment]
Great, Thanks @matklad !

**Comment by lucax88x** [comment]
@jakub-wojciech @matklad @sho-87 

hooray!
released 1.1.10 with the 'workaround', thanks to @matklad
