### ISSUE TITLE
feature request: add command to select from current position to the jumped position

### ISSUE THREAD

**Issue by metasong** [lucax88x/CodeAceJumper#12]
add another command to do selection.
to select from current position to the jumped position

**Comment by metasong** [comment]
thanks for your quick respond

**Comment by lucax88x** [comment]
I've released a new command, AceJump: Selection which does what do you want.

However, in the future when I have more time, I might totally rework it and use something more intelligent like the `set mark` of emacs.

Let me know what do you think!

**Comment by metasong** [comment]
cool!
