### ISSUE TITLE
feature request: to make the jumper faster--placeholder show more charactor when more are indexed

### ISSUE THREAD

**Issue by metasong** [lucax88x/CodeAceJumper#13]
yes, we have https://github.com/lucax88x/CodeAceJumper/issues/6
what about when there are more placeholder we show more than one letter, this will let user type quickly, no need to wait to show the second level placehoders and then type to jump.

i.e.
currently: a, a, a,a, b,c,d
what about: aa,ab,ac,ad,ae,a,b,c,d

may be a better one:
aaa,aab,aa,ab,**a,b(cursor),c,d**,ac,ad,aac,aad

more information show to the user at the first step, so the user would type quickly,
another idea is let the user config the max placehoder characters shown, i.e if set 2:
the above example would be like this: aa,aa,aa,ab,**a,b(cursor),c,d**,ac,ad,aa,aa
and need the second level placehoder.

by the ways: thanks for the selection command

**Comment by lucax88x** [comment]
uhm.

this is a good idea indeed, that I'm wondering why I didn't think about this before.

there must be an explanation I forgot, I'll take a look on this!

**Comment by metasong** [comment]
thanks for quick response!!

**Comment by metasong** [comment]
I think about this again and found another similar solution:
asume we have frequence based charactors set {j,k,f,d}, j is more easy to type, then k, then f
if we display 2 charactors to user, the combination are 4*4. 
so:     dj,dk  fj,fk   kk, kj,    jk, jj,     k, j(cusor)f,d     ,jf,jd,     kf,kd   ff,fd   df,dd

if using 26 english charactor, the 2 charactor combination(26*26)is enough for the viewable region

**Comment by Nxt3** [comment]
You could look to this source for how to implement this: https://github.com/wmaurer/vscode-jumpy

It hasn't been updated in a while and yours is more current.

**Comment by lucax88x** [comment]
closing this in favor of #26
