### ISSUE TITLE
selected text limitation

### ISSUE THREAD

**Issue by csalv5** [lucax88x/CodeAceJumper#14]
I think it should be given as an option.

**Comment by lucax88x** [comment]
Sorry, can you be more specific? I did not understand your request

**Comment by csalv5** [comment]
Sorry, i mean when i trigger AceJump while some text is selected, the search is limited to the currently selected text. Is there a way to remove this restriction (so that it continues to search in the entire viewable region)? Or at least provide an option to change this behavior.

**Comment by lucax88x** [comment]
Yeah, I can add an option in order to disable this feature, sure!

**Comment by csalv5** [comment]
Great news, thanks! 
Also, any plans to add [this](https://github.com/ice9js/ace-jump-sublime/blob/master/README.md#character-mode) feature? I mean jump to any middle letter of a word...not only the first.

Anyhow, nice extension, keep it up

**Comment by lucax88x** [comment]
now there's possibility to skip the search on the selections using the new setting `aceJump.finder.skipSelection=true`

**Comment by lucax88x** [comment]
regarding the other feature you requested, I had already opened this [issue ](https://github.com/lucax88x/CodeAceJumper/issues/9), and as you can see, I've just released this new setting on the 1.1.5 along with this issue

**Comment by lucax88x** [comment]
Released with 1.1.5 version of extension

**Comment by csalv5** [comment]
Wow, really fast...thanks a lot!
