### ISSUE TITLE
feature request: adopt aceJump visual

### ISSUE THREAD

**Issue by itainoam** [lucax88x/CodeAceJumper#15]
Purely a visual improvement.
AceJump in emacs has a subtle and beautiful effect where the background loses colors and only the search key is in color. Would be nice if it was possible.

The effect can be seen in this video:
[http://www.youtube.com/watch?v=UZkpmegySnc&t=0m54s](http://www.youtube.com/watch?v=UZkpmegySnc&t=0m54s)

**Comment by lucax88x** [comment]
@itainoam I'm afraid the API of vscode does not permit to programmatically

we will track this Microsoft issue https://github.com/Microsoft/vscode/issues/20997 in the hope they will implement this

**Comment by lucax88x** [comment]
Will be mitigated by #27
