### ISSUE TITLE
Selection of jump points for Python code

### ISSUE THREAD

**Issue by pe224** [lucax88x/CodeAceJumper#150]
Thanks for this cool extension.
Given the following sample Python code
```python
def main():
    param1 = 1
    param2 = get_param()
    return first_function(param1, param2)
```
when trying to jump to a closing bracket `)` I can only do so where there are no function arguments:

![image](https://user-images.githubusercontent.com/8567333/72810152-483ffe80-3c5d-11ea-9d20-33356b0b98b9.png)

Jumping to the colon `:` is not possible at all.

Is this by design, i.e. by definition of a "word"?

**Comment by pe224** [comment]
I noticed that this can be fixed by setting
`"aceJump.finder.pattern": "[ ,-.{}_()\"'<>\\[\t]"`
in the config.
Note, I added the closing characters `}` `)` `>` to the original regex.
Does this have any unintentional side effects?

Unfortunately, adding `\\]` in a similar way does not resolve #34.

**Comment by lucax88x** [comment]
Nah, I don't think there's any unintentional side effects, It's open to the user to define it's character where he wants to ace jump, the original pattern is what was good for me, but in the time I extended it for my other own use cases.

So it's the issue fixed by changing the pattern?

**Comment by pe224** [comment]
Yes, I'll close it since the original question for `)` can be fixed that way.
It still leaves the mentioned issue regarding `]` open, but it seems you're already on it 👍 👍
