### ISSUE TITLE
[Enhancement] Refresh jump indices when visible region changes

### ISSUE THREAD

**Issue by pe224** [lucax88x/CodeAceJumper#151]
As an idea, would it be possible to update the jump indices when you change the visible region?

E.g. looking a the jump indices for `a`, after pressing `PageUp` or `PageDown` a couple of times, the jump indices would update to the `a`'s in the new region.

**Comment by lucax88x** [comment]
That's pretty good idea, I'll need to check if it's feasible..

**Comment by lucax88x** [comment]
@pe224 

Should be feasible, I found these events there.

onDidChangeTextEditorVisibleRanges
onDidChangeVisibleTextEditors
onDidChangeTextEditorSelection

Need to try these out.

btw, this morning I released the 2 PR you did, were you able to try them?

**Comment by pe224** [comment]
Yes, I got the recent version - pretty cool :sunglasses: 
I'm currently trying to add another (hopefully useful) feature.
I'll write a quick issue adding some of the stuff I've tried.

**Comment by lucax88x** [comment]
What do you think about this?

https://webm.red/HF4I

**Comment by lucax88x** [comment]
@pe224  Released in 3.0.0
