### ISSUE TITLE
Make the extension globally available (without installing remotely)

### ISSUE THREAD

**Issue by pe224** [lucax88x/CodeAceJumper#153]
When using the remote development tools of VSCode (e.g. SSH, WSL or containers), some extensions can be used without the need to re-install on the remote system.

Unfortunately, CodeAceJumper is not (yet) one of them. When running remotely on e.g. WSL, I need to install it into the remote system to use it:
![image](https://user-images.githubusercontent.com/8567333/72910343-b3123800-3d38-11ea-8015-a8b7b33e34aa.png)

Buffer navigation feels pretty "local", so would it be possible to make this extension work in remote sessions without explicit install?
Maybe [this](https://code.visualstudio.com/api/advanced-topics/remote-extensions) helps?
Could it be converted into a "UI extension"?

**Comment by lucax88x** [comment]
Thanks, I'll try to check in my free time ;)

**Comment by pe224** [comment]
It seems, adding the following lines to `settings.json` is already enough for it to be fully functional remotely without installation
```json
"remote.extensionKind": {
    "lucax88x.codeacejumper": ["workspace", "ui"],
},
```
In the extension's [package.json](https://github.com/lucax88x/CodeAceJumper/blob/master/package.json) this can be fixed by adding `"extensionKind": ["workspace", "ui"]`.

Putting it in this order (first `workspace`, then `ui`) should actually not change anything when it is run locally and only switch to `ui mode` when run remotely.

However, information on the capabilities/permission for `ui` vs `workspace` were somewhat sparse, but in quick testing I didn't notice any negative effects.
