### ISSUE TITLE
Is MultiChar broken?

### ISSUE THREAD

**Issue by Raikiri** [lucax88x/CodeAceJumper#159]
I have not used older versions of this extension, but right now when I enter MultiChar mode (via ctrl+shift+p) and then enter one symbol with multiple matches, it highlights them all and the status bar says "Next char". However, when I enter the next character, it exits the mode and the status bar says "Cancelled". Is it broken or am I doing something wrong?

**Comment by lucax88x** [comment]
We released a bugfix this morning, so I thought we may have broken this, but the tests were running fine and I just tried and it works perfectly to me. Can you be more detailed? Screenshots / video or something like that.

**Comment by Raikiri** [comment]
I think the problem is maybe that I don't understand exactly what it's supposed to do. I expect it to work like this. In this text, say, I want to jump to the second "t" in word "test03":
![image](https://user-images.githubusercontent.com/1657728/73086337-592a9180-3f35-11ea-9da6-8f5291dffba4.png)
so I invoke MultiChar via ctrl+shift+p and hit "t":
![image](https://user-images.githubusercontent.com/1657728/73087006-9cd1cb00-3f36-11ea-8203-eee941fcc2c6.png)

then I expect to continue typing "03" till it finds that "test03" is the only string that satisfies and lets me jump there. Instead as soon as I type "0", it just closes the search and says "Cancelled" in the status bar, no movement occurs. 

Strangely enough, I am able to do some other searches: for example, I can type "est0" and I get this:
![image](https://user-images.githubusercontent.com/1657728/73087047-b115c800-3f36-11ea-83e4-68193c311f15.png)
However, all of the jump anchors are "a" for some reason when I expect them to be unique. Or if multiple anchors are the same, I expect it at least to give me prompts for further pinpointing same how normal Jump does, however, it just jumps to the first anchor when I hit "a".

**Comment by lucax88x** [comment]
Regarding the first case, no. you need to write all the word, so you gotta write T E S T 0 3 if you want this one.

Anyway, your idea is good one... As writing T and then 03 would be a better way to reach Test03.

Regarding the second case, I think you hit a bug.

When there are more occurrences of the searched char than the alphabet, it tries to group the possible occurrences in order to try to match every character possible (there are many A and B as you can see).

Multichar is pretty a recent feature and I neverthought about grouping and multichar together..I'll take a look at this particular case even it's a particular one.

**Comment by Raikiri** [comment]
> so you gotta write T E S T 0 3 if you want this one.

Problem is, as soon as I hit "E" in "test03" it cancels the search and does not jump anywhere.

I'm still confused what it's supposed to do. Like, how is the program supposed to distinguish if I'm hitting an anchor and want to jump to it or I'm continuing to enter a search query? What other programs do for example is they remove anchors that are also continuations of words so that there's no ambiguity. Or if you type a special symbol (say, space) then it considers next symbol that you input to be an anchor instead of entry continuation. Space is extremely fast to type so it almost does not increase search time.

> I'll take a look at this particular case even it's a particular one.

Thanks. FYI though, I'm not playing with synthetic tests, I was genuinely trying to understand how MultiChar works on my actual source code and whatever I tried, just did not work at all.

**Comment by lucax88x** [comment]
this is the easiest use case https://webm.red/8mxZ for multi char. Does it work for you like that?

What it's missing, like you said, the possibilty to 'cancel' the search by a special symbol (space is perfect) and consider the next a jump anchor.

I'll add a task for that.

**Comment by lucax88x** [comment]
in the meantime I fixed you problem regarding #160,  still not deployed

**Comment by Raikiri** [comment]
Thanks for looking into it.

> this is the easiest use case https://webm.red/8mxZ for multi char. Does it work for you like that?

It does work for me like that for some strings: in example above it does work similarly with a string "est03". However, for other strings it just cancels as soon as I type the second character, for example if I try to type "test03" it cancels when I type "e".

**Comment by lucax88x** [comment]
btw, regarding the 'cancel' it's already implemented. you can press ESC to stop the search and then you can jump..

when I got some time I'll try your test case..
