### ISSUE TITLE
[Enhancement] Add a "jump to beginning of line" command

### ISSUE THREAD

**Issue by pe224** [lucax88x/CodeAceJumper#162]
For an example, see the gif [here](https://github.com/wmaurer/vscode-jumpy).
This would be a command to show the placeholders at the beginning of each line to easily jump there, e.g. also to empty ones.
As a command, it can, of course, be hotkeyed directly (and separately from the other aceJump commands), but regarding UX it would be nice to also be able to have a hotkey for it when one has already entered AceJumpInput mode.

Some technicalities:
It's easy to get the `lineIndexes` for the start of each visible line.
However, simply doing this in the current code, the placeholders for empty lines are not shown, since you actually put them [one character to the right](https://github.com/lucax88x/CodeAceJumper/blob/master/src/placeholder-decorator.ts#L45-L48) and use the `after` [with a negative margin](https://github.com/lucax88x/CodeAceJumper/blob/master/src/placeholder-decorator.ts#L35-L38) to make the placeholder overlap with the original character.
This does not work with an empty line as the placeholder is then "pushed out" to the left of the area (where the line numbers are) and is not visible anymore.

From my limited understanding I see two ways:
* define a separate decorationType for empty lines which does not do the negative margin shift (I've got this version working more or less, but it just feels a bit too hacky)
* see if the negative `margin` trick is necessary at all, since https://github.com/wmaurer/vscode-jumpy seems to achieve a nice overlapping without using `after`/`before` or anything else. I have not yet checked how/why this actually works.
This might mean that people cannot specify the x/y coordinate of the placeholders anymore... but I guess most people configure it anyways so that the placeholder overlaps directly with the desired character(?)

**Comment by lucax88x** [comment]
Would it really be useful? I m always jumping to a specific word more that a line..

**Comment by lucax88x** [comment]
@pe224 Implemented.

https://webm.red/view/oUCT.webm

What do you think?

**Comment by lucax88x** [comment]
Released with 3.1.0

**Comment by pe224** [comment]
Very cool, thanks for your recent fix/feature explosion!

I have a question how to setup the "hotkey" idea in the feature description.
I would like to use `ctrl+k` to activate line jump mode, but only when I'm in aceJumpInput mode (to keep normal usage of `ctrl+k` otherwise).

For this, I tried to add the following keybinding
```
{
    "key": "ctrl+k",
    "command": "extension.aceJump.line",
    "when": "aceJumpInput && editorTextFocus",
}
```

However, after going into jumpmode and pressing `ctrl+k`, the statusbar displays "Canceled", but I'm still in jumpmode.
Is it possible to activate line-jumpmode directly when in input mode?

Another thing which just came to my mind and goes into the same direction:
it would be nice if one could jump to a line beginning also in Selection mode

All in all, it feels like instead of being its own command, line-jumping should be part of the already existing jump logic. Is this achievable?

Edit: pinging @lucax88x

**Comment by lucax88x** [comment]
@pe224  Sorry, I'm always really busy at job :(

I'll check if it's doable (the possibility to switch to commands ASAP) but I don't have high hopes.

Regarding the inclusion of line-jumping included on existing jump logic, I'll think about this, and maybe make this optional.

**Comment by pe224** [comment]
@lucax88x 
Don't worry. Please take your time, I appreciate it.
The reason for the ping was because I was not completely sure if you receive a notification for comments in already closed issues 😄

I wonder if you can catch hotkey combinations in your aceJumpInput or just single characters...
