### ISSUE TITLE
Replacing anchor placeholder with just a decoration

### ISSUE THREAD

**Issue by Raikiri** [lucax88x/CodeAceJumper#164]
As far as I understand, currently there's a whole placeholder svg image placed over the text with a symbol on it to show what the hotkey for jumping (anchor) is. This approach is very fiddly as it requires careful placeholder symbol placement, font size and position choice and sometimes readability suffers when zooming or when an entire symbol (for w, m, etc) does not fit into the placeholder. Even then, it feels out of place when anchor symbol does not align perfectly with the rest of the text.

However, looks like multichar mode uses a simpler method of adding decoration to text to show matching symbols. Why not use the same tech for rendering anchor symbols? In my opinion, it's simpler and and is also by design guaranteed to match user's font and zoom settings perfectly as it uses exactly the same font with different colors.

**Comment by lucax88x** [comment]
Yeah, keep in mind that multichar decoration came after 2 years since the first implementation, however when I implemented the decoration stuff I came to the same conclusions as yours, and I am pretty sure that something wasn't possible, like you can only decorate existing texts and you cannot add 'text' as decoration so that is not feasible..

**Comment by Raikiri** [comment]
Well, this is how they implement it in some other similar extension (https://github.com/mbnuqw/jumpt) and it works perfectly fine.

**Comment by lucax88x** [comment]
Ok, now I remember what the issue was.

![https://i.imgur.com/EzJZZnJ.png](https://i.imgur.com/EzJZZnJ.png)

Can you notice the issue with decorations? We cannot go ABOVE letters, it shifts everything.. :(

Can we go with that?

**Comment by lucax88x** [comment]
MM, let me check, the example you linked is not having this issue..

**Comment by Raikiri** [comment]
Yeah I think something's wrong with what you're doing because in that extension there's no fancy code happening here. just a decoration that replaces characters with other characters and formatting is perfectly fine.

There's just one problem that I'm aware of here: you can't replace chars that occupy more than 1 cell that way. As in, you can replace a tab character like this, but your formatting will slide because of that.

Btw another thing that extension is doing is showing an edit field for the current multichar seach. It's very convenient to edit it, close it and generally see what you've entered.

**Comment by lucax88x** [comment]
@Raikiri new release is coming soon

**Comment by lucax88x** [comment]
@Raikiri  Released in 3.0.0
