### ISSUE TITLE
Can't define keybindings, get error: command with id already exists

### ISSUE THREAD

**Issue by wd** [lucax88x/CodeAceJumper#17]
I've tried to define my keybinding, 
```
    {
        "key": "alt+s",
        "command": "extension.aceJump"
    }
```

No matter what keys I use, always get error: command with id already exists, and the binding not work, don't know what to do ...

**Comment by lucax88x** [comment]
Weird,  I'll have a look when I am back from the sea!

**Comment by lucax88x** [comment]
Can you give me the extensions you have installed? I'm afraid you have the same problem of #11

**Comment by wd** [comment]
Yes, maybe the same problem. I'm using "Emacs Keymap" 0.1.1 to remap my keys.
