### ISSUE TITLE
"AceJump: Jump To" message always in status bar

### ISSUE THREAD

**Issue by DavidBabel** [lucax88x/CodeAceJumper#18]
This extension is quite perfect, except for the always shown message in tool bar "AceJump: Jump To", even when i don't use the plugin : 

![image](https://user-images.githubusercontent.com/5599375/29664767-60d966e4-88d1-11e7-8e1d-fdb0ace13fa5.png)

**Comment by lucax88x** [comment]
Yeah I noticed that too, need to fix asap. Thx!

**Comment by lucax88x** [comment]
sorry for lateness @DavidBabel .. now version 1.1.7 should be deployed with the fix!
