### ISSUE TITLE
Feature request: allow to search for two-character sequences

### ISSUE THREAD

**Issue by alexeygrant** [lucax88x/CodeAceJumper#21]
I think it would be great to to be able to search for two-character sequence as it greatly reduces number of clues to jump to, and in most of the cases eliminate two-characters clues.

**Comment by lucax88x** [comment]
I'll have to create a specific command for that, I cannot use the original one, agree?

**Comment by VisionaryAppDev** [comment]
I am thinking of helping this feature but take hours to read the code and only understand some of them lol. So, I think I could not help at all and I think if you could add more features to it like **avy-goto-char-timer** or **avy-goto-line** which abo-abo/avy has then it would be great!

**Comment by lucax88x** [comment]
@VisionaryAppDev  100% agree with you, code is a mess, that project started 3 years ago like a game, never expected it to be so used.

**Comment by lucax88x** [comment]
Want me to add 1 new commands for this, and refactoring in a way so you can add the other one?

**Comment by VisionaryAppDev** [comment]
Yes, I think so. Refactoring and add some comments to explain it so another can help extend this project when they need and I will to if I could.  Specifically, *placeholder-calculus.ts* file is the hardest I guess because I am not if it has something to do with calculus.

**Comment by Streppel** [comment]
Hey, came here specially to search for a thread like this. I suspect you could use the same shortcut as well, just keep concatenation going until it hits an escape character - at least that's how ace jump behaves on IntelliJ idea.

Edit: uploaded a better gif
![mygif](https://user-images.githubusercontent.com/2300328/53043799-17ad7e80-3468-11e9-993e-9d425a9801e8.gif)

**Comment by Streppel** [comment]
@lucax88x are you doing a refactor at the moment?

**Comment by lucax88x** [comment]
@Streppel Yes, I'm starting the refactor these days. Just don't have that much time but I'll find some.

I like the idea of the gif above, I'll try to think about it, but for beginning I think that we will just restrict placeholders when we type the 2nd (and so on) character until we press the escape character like you said.

**Comment by lucax88x** [comment]
Current status for who is interested:

- [DONE] introduced tslint, prettier and much more strict tsconfig & adapted code
- [DONE] added tests to cover all possible cases
- [TODO] starting the refactor & documentation

**Comment by lucax88x** [comment]
The feature is almost completed:

this is how it works:

1) there's a new command, so the original one is preserved (with single letter)
2) when you start this new command, you have to type your first char, then the yellow placeholder appears for every start letter matching the char
3) you can start write characters, and the next letters will be highlighted with the green (like the gif), but
- if the next character matches nothing, the previous placeholders & highlight will be kept
- if the next character matches at least one letter, placeholder & highlight will be restricted but preserving order, so if I had placeholders A, B, C, and the A, C are restricted you will only see A, C placeholders in the screen, with the highlights
4) a max of 5 character restriction if allowed, when the 5 characters are reached the next char is considered as the placeholder where you want to go
5) during this 'restriction' phase you can always still press the escape button and your next char will be consiered as the placeolder where you want to go

questions:

1) should the escape button be configurable?
2) is the 5 char limitation ok for you? want more? can't to infinite..
3) is the flow ok for you?

**Comment by lucax88x** [comment]
Ah, and I'll make a gif asap in order to make it more clear

**Comment by Streppel** [comment]
@lucax88x Thank you for the heads up! Great! Personally, I believe that 5 chars should be more than enough, however I'm rather curious to see the reason why adding an unlimited amount of characters would be a problem... 

Anyway, I'm happy with this flow (though personally I have to admit I'll replace the single character command with this new one - disabling the single character completely. But that's me: having one command to search for everything instead of two makes my life easier). Regarding the escape button, I really can't think of any better key than esc (given that the escape button does what I think it does) for this purpose. Unless you have one of those gimmicky touch bar MacBook pros, of course.

**Comment by lucax88x** [comment]
Yeah, the reason is that, for now, creating the highlight is done the same way as placeholders are created, meaning that we create SVG and use them as decorator, this is not ideal and I need to find a better solution, I would just want to 'highlight' a character..

**Comment by Streppel** [comment]
@lucax88x I see. Maybe we'll need to work on that... One good repository to take a look at is the [IntelliJ plugin page](https://github.com/acejump/AceJump). I'll check your implementation after you merge your changes, and maybe we can think of something together. 

One interesting note: this repo is not listed in the similar software section! I'll add it :+1:  from this thread I can see that we have a good amount of people interested in this repo.

**Comment by lucax88x** [comment]
Yeah its the only part I am not so happy about.

Yep you can add it! but what do you mean?

**Comment by Streppel** [comment]
@lucax88x sorry, what do I mean by what?

**Comment by lucax88x** [comment]
:D sorry.

I meant by adding it so "similar software section"

**Comment by Streppel** [comment]
@lucax88x take a look at the Acejump’s readme file. I’ve added a link to your repo there

**Comment by lucax88x** [comment]
got it! thx!

**Comment by Streppel** [comment]
@lucax88x just out of curiosity, when do you plan on merging the changes? (this may sound pretentious but I'm really just curious)

**Comment by lucax88x** [comment]
@Streppel  Yeah sorry, I'm always pretty busy and working on it only on free time. I'll correct a couple of tests this morning and then push what I have.

**Comment by lucax88x** [comment]
@Streppel pushed, you can give a try, the command is extension.aceJump.multiChar

I'm just starting add tests on this feature right now, then will try to improve the highlight thing

**Comment by Streppel** [comment]
@lucax88x cool! thanks! I'll take a look into it later, will let you know if I find any bugs or anything

**Comment by lucax88x** [comment]
@Streppel  lemme know, I am pretty curious!

**Comment by Streppel** [comment]
@lucax88x looks pretty consistent so far! Congratulations!

I believe the right thing to do now is to mark this issue as done and take future development further with different issues whenever they're needed.

**Comment by lucax88x** [comment]
Ok, if I find some time tomorrow Ill polish and publish this as 2.0.0

**Comment by lucax88x** [comment]
Released 2.0.0

**Comment by lucax88x** [comment]
@Streppel in the 2.1.4 there's a new way to render the highlights using background-color instead of svgs, therefore its much more precise and theres no limitation of 10

**Comment by Streppel** [comment]
@lucax88x this is beautiful :) I'll check it out!
