### ISSUE TITLE
Any issue on last vscode release ?

### ISSUE THREAD

**Issue by DavidBabel** [lucax88x/CodeAceJumper#22]
I cannot make it working anymore on last VScode April 2018 1.23

Is there anything to change ?

**Comment by lucax88x** [comment]
I just tried with my vscode like every day and everything is working pretty fine.

Did you install any other extensions like the emacs one?

**Comment by lucax88x** [comment]
@DavidBabel  any news?

**Comment by DavidBabel** [comment]
Sorry, i need to test it again next week. Havn't my computer with me for days.
