### ISSUE TITLE
Wrong order of line-ending 2-char placeholder (ending in 'a')

### ISSUE THREAD

**Issue by pe224** [lucax88x/CodeAceJumper#228]
![codeacejumper-bug](https://user-images.githubusercontent.com/8567333/79269683-2392a600-7e9d-11ea-883c-3759e3bff190.png)

Red-marked 2-char placeholder `ab` should actually be `ba`.
The wrong order seems to happen only when following conditions are true:

- it's a 2-char placeholder (introduced in #201), so it only occurs on line endings or on empty lines
- the 2nd letter is an `a`, so for `ba`, `ca`, `da`, ...

I suspect something is fishy in the [concatenation to create the 2-char placeholder](https://github.com/lucax88x/CodeAceJumper/blob/0054ce5b026f80eceef8de7c104e06a1e6edb4aa/src/placeholder-decorator.ts#L40-L44) for the placeholders involving an `a` as 2nd character, as they are IIRC somehow "special-cased" in the placeholders array (i.e. `ba` appears with `b` as child of letter `a`, whereas `bb..bz` appear with `b..z` as children of letter `b`)

**Comment by lucax88x** [comment]
Yeah, some edge case, it's probably happening also on ac? Anyway, as you worked on this part, can you create a fix for that?

**Comment by pe224** [comment]
That should (hopefully) be it 👍

**Comment by lucax88x** [comment]
Released 3.3.2!
