### ISSUE TITLE
Ace jump labels should not move surrounding text

### ISSUE THREAD

**Issue by matklad** [lucax88x/CodeAceJumper#23]
Hi!

Currently, AceJump's labels affect the rendering of surrounding text:

![image](https://user-images.githubusercontent.com/1711539/43255169-c6c5456e-90d1-11e8-9ae6-78a5d0b9777e.png)

Here, both lines should have the same length, height and baseline, but the top one is distorted because of the label.

**Comment by lucax88x** [comment]
Ehi, thanks for reporting this.

I'll try to have a look at this, but I'm pretty much afraid there's not much we can do on this.. :(

**Comment by lucax88x** [comment]
Right now, the yellow thing will always move the TEXT on the right, but it shouldn't corrupt the height of the row, did you try to adjust the height of the placeholders? It's configurable

**Comment by matklad** [comment]
It does move the baseline I think:

![image](https://user-images.githubusercontent.com/1711539/43316198-22cf0d2a-91a1-11e8-81f9-d044fd56cc96.png)

![image](https://user-images.githubusercontent.com/1711539/43316224-49797a82-91a1-11e8-8c41-c1a0082f2ce2.png)

But yeah, I have a non-default height, if I make it smaller the vertical position is preserved.

**Comment by matklad** [comment]
But yep, I totally get why it might be a won't fix, the VS Code API is pretty limited :( 

I wonder if it is possible to abuse `textDecoration` property of https://code.visualstudio.com/docs/extensionAPI/vscode-api#DecorationRenderOptions to inject a styled marker with letter via CSS...

**Comment by lucax88x** [comment]
originally it was a marked letter by css, but it caused severe performance bottlenecks.

now it's a svg image with an height & width, maybe is there any possibility to make it floating in the editor and then you have to absolute position it.. maybe..

I asked some help here.. let's see..

https://stackoverflow.com/questions/51555405/vscode-setdecorations-changes-the-oustide-text-rendering

**Comment by matklad** [comment]
Might be a good idea to check how this extension solves the problem: https://marketplace.visualstudio.com/items?itemName=wmaurer.vscode-jumpy

**Comment by lucax88x** [comment]
Oh, this is the extension where I took some inspiration, I didn't notice this... I'm gonna check, thanks mate! ;)

**Comment by lucax88x** [comment]
@matklad  I just tried jumpy, despite the gif, it's actually moving the characters like the mine does, did you try it?

**Comment by matklad** [comment]
@lucax88x I've actually switched to meta-go extension, it doesn't move characters:

![image](https://user-images.githubusercontent.com/1711539/43450204-dd954cc0-94ba-11e8-9e83-9b13b2dcc311.png)

**Comment by lucax88x** [comment]
@matklad  just fixed it ;) releasing in minutes.

**Comment by lucax88x** [comment]
Released 1.1.8
