### ISSUE TITLE
When two chars are required for the jump, show them both

### ISSUE THREAD

**Issue by matklad** [lucax88x/CodeAceJumper#26]
Hi! If there are many matches, user needs to type two chars to get to the match. 

In the current UI, two char seqs break the flow, because there's no indication that two chars are required. That is, I see a char, I type it, and I expect to be at the target location, but instead the second target char is shown. The fact this happens rarely also contributes to distraction.

I believe emacs uses the same confusing UI. I suggest taking a look at how ace-jump lite plugin for IntelliJ does this: it shows two chars together, so one can easily chord them.

A picture is worth a thousand words:

CodeAceJump:

![image](https://user-images.githubusercontent.com/1711539/55006462-da9c5500-4fee-11e9-9782-bf1f29e4d53d.png)

Emacs:

![image](https://user-images.githubusercontent.com/1711539/55006486-e5ef8080-4fee-11e9-8dfb-9e566f06cd7d.png)

IntelliJ (:heart:)

![image](https://user-images.githubusercontent.com/1711539/55006539-f69ff680-4fee-11e9-89fb-919fca77783a.png)

Two-char sequences are shown with two colors.

**Comment by lucax88x** [comment]
Nice idea, what you want is to just "pre-show" the 2nd character in the case it's grouped?

Will be studied later.

**Comment by matklad** [comment]
>what you want is to just "pre-show" the 2nd character in the case it's grouped?

Yep. Though, there might be some other UI tricks to make 1 char vs 2 chars clearer. For example, we can always show only the frist/single char, but draw it in a different color if there's a second one required.

**Comment by lucax88x** [comment]
Yep like the final gif

> > what you want is to just "pre-show" the 2nd character in the case it's grouped?
> 
> Yep. Though, there might be some other UI tricks to make 1 char vs 2 chars clearer. For example, we can always show only the frist/single char, but draw it in a different color if there's a second one required.

**Comment by Nxt3** [comment]
You could look to this source for how to implement this: https://github.com/wmaurer/vscode-jumpy

It hasn't been updated in a while and yours is more current.

**Comment by lucax88x** [comment]
I promise I'll have a look at this feature in the next weeks, now I'm pretty busy :(

**Comment by lucax88x** [comment]
@Nxt3 @matklad @csalv5

What do you think? 

![Screenshot_2020-02-18_20-19-07](https://user-images.githubusercontent.com/6294464/74770266-310c2500-528c-11ea-8009-90e1f8bbd704.png)

Released with 3.2.0!

**Comment by matklad** [comment]
*Perfect*, thanks a bunch!
