### ISSUE TITLE
MultiCharacter search doesn't work

### ISSUE THREAD

**Issue by sygutss** [lucax88x/CodeAceJumper#28]
Hi, guys ;) firstly I would like to really thank you for your job.
Unfortunately, the new feature multi-character search doesn't work correctly.

Example: 
In the attached movie in the zip, I would like to go to the "sentence" word in the second sentence.
[Screen Recording 2019-03-30 at 20.26.05.zip](https://github.com/lucax88x/CodeAceJumper/files/3025874/Screen.Recording.2019-03-30.at.20.26.05.zip)

**Comment by lucax88x** [comment]
Thanks and appreciated your feedback! Weird, did you escape with esc button before pressing F?

**Comment by sygutss** [comment]
Yep... that's my problem I didn't escape with esc button before.
I'm similar with the Ace jump for Pycharm and there you don't have to do it before.
Sorry for my misunderstanding. You can close the ticket.

Suggestion:
You should change the approach with escaping by esc before choosing a letter, it's a little bit uncomfortable. Will be nice if it will work like in jet brains stuff.

Anyway 
Great job guys ;)

**Comment by lucax88x** [comment]
I am actually open to suggestions, how it should work in your opinion? 

- if the pressed char matches the next letter in the editor, it restrict it and shows new placeholders
- if the pressed char does not match a letter but matches a placeholder it should jump to it, without escaping

the second option would be the new feature I could implement.

**Comment by sygutss** [comment]
Yes for pycharm from jet brains  it works like you described above :) without escaping char, so I will be waiting for the next release :D which will contain this new feature :)

And we can close this one because now I'm know that's not a bug :)

**Comment by lucax88x** [comment]
Yeah, working on it this evening, shouldnt be hard.

**Comment by lucax88x** [comment]
@sygutss  Released 2.0.1, let me know if it works as expected.

**Comment by sygutss** [comment]
Man, it works awesome :) like in Pycharm :D
With one small difference. if only one match left
they should show only one possibility to jump instead of jumping automatically
I attached examples of the plugin from Pycharm and vs code ;)
[pycharm_example.zip](https://github.com/lucax88x/CodeAceJumper/files/3031133/pycharm_example.zip)
[vs_code_example.zip](https://github.com/lucax88x/CodeAceJumper/files/3031134/vs_code_example.zip)

The rest works pretty nice :D
You can also add the possibility to turning on and off showing the window to search.
Sometimes is not comfortable when we have a lot of text because then text is under the window on which is showed on the top.
Now I can start using multi-char search :)
Very great job ;) 👍

**Comment by lucax88x** [comment]
You are welcome.

Well, aren't you now asking to make it behave like it was before?

In the vscode you are typing S, E, and then C which is not only the 3rd letter of a word but also a placeholder and also the only match, why you would want to restrict it more?

Isn't pycharm instead of jumping just restricting for nothing and wasting your time?

Btw, regarding the window, I don't have it, so I guess it's configurable by vscode but I don't know which setting it is :( I'll try to look for it.

**Comment by sygutss** [comment]
Isn't pycharm instead of jumping just restricting for nothing and wasting your time?

No its not because if you start very fast typing to search something, now you get imidietly jump to the place and type something from search string before the word, then you have to delete this and continue work. In pycharm we don't have this type of situation because jump is always doing by you and you know when you are jumping, it's not automatically. But without any escape character like before.

**Comment by sygutss** [comment]
In the case of the top window, it's probably caused by the fact that I work on MacBook. As far as I know, this window doesn't show on Windows operating system.

**Comment by lucax88x** [comment]
based on what you said, the first gif you posted on this issue was fine then?

**Comment by sygutss** [comment]
Hmm probably yes, it hard to say for me. 
In the previous approach, we should escape by esc key before choosing the place.
In pycharm we don't have to do it :)

Anyway, great job man.
For me, even this approach is quite well 👍

**Comment by lucax88x** [comment]
But the first gif is now behaving like pycharm, because you don't have to press ESC anymore.
