### ISSUE TITLE
Apply dim only after the head character is typed

### ISSUE THREAD

**Issue by matklad** [lucax88x/CodeAceJumper#30]
Just tried out the new dim feature, it's super cool!

However, it works a bit differently from Emacs: CodeAceJumper applies dimming immediately after you invoke it (at least, with on-type handler work-around enabled), white Emacs waits until the search character is typed. 

I think Emacs behavior is slightly better here: until you've typed the search char, you are interested in the original buffer contents, so dimming does not really helps.

**Comment by lucax88x** [comment]
I agree with you, gonna do it today.

**Comment by lucax88x** [comment]
Released 2.1.3

**Comment by matklad** [comment]
tired this out, works *perfectly*, thanks!
