### ISSUE TITLE
When jumping in selection mode, place cursor such that the jumped to character is selected

### ISSUE THREAD

**Issue by matklad** [lucax88x/CodeAceJumper#31]
Currently if I use ace jump with selection to select *forward*, the last char is not selected.

For example, if I want to select `{ this block}`, and the cursor is on `{`, acejumping to `}` selects only `{ this block`. I think for forward selection it makes sense to jump *after*  the `}`.

**Comment by lucax88x** [comment]
I will be honest, I tried to read this issue three times, but haven't figured it out yet.

Why it should jump forward?

**Comment by matklad** [comment]
I am actually not sure this is a good idea anymore myself.

The problem I see is that the semantics of "jump with selection" is different depending on whether you jump forward or backward.

If you jump *forward* to char `x`, the `x` *is not* selected. 
If you jump *backward* to char `x`, the `x` *is* selected. 

If you want to have precise selections after jump, it would be better if it worked the same way regardless of the direction of selection.

But after using this feature for a while, I am not sure if precise selection is possible at all: given that you jump to the beginning of words, you can't select something up to a word end.

I guess it's better just to close this issue, with a mental note that "jumping with selection is not as precise as it could be, for various reasons"
