### ISSUE TITLE
jump to multichar some times dost not work

### ISSUE THREAD

**Issue by shelper** [lucax88x/CodeAceJumper#32]
have no idea why is that but for some mutichar bindings for some particular txt files, the extension fails to behavior as expected, for example this file, if you open it in vscode using 2.1.4 acejump, i cannot use multichar to jump to "re", "se", to name a few

[example file fail to jump to ](https://github.com/Lectem/cpp-boilerplate/blob/master/CMakeLists.txt)

**Comment by lucax88x** [comment]
can you post a webm / gif ? or tell me which word is not working? It's working fine for me
