### ISSUE TITLE
When set to "only initial letter", first word of each line is ignored in tab indented code

### ISSUE THREAD

**Issue by ZYinMD** [lucax88x/CodeAceJumper#33]
If my code uses tabs instead of spaces for indentation, and I turn on "only initial letter", the first word of each line won't be targeted.

**Comment by lucax88x** [comment]
Thanks, I'll check asap!

**Comment by ZYinMD** [comment]
I did an easy fix by adding `\t` in the regex pattern. I'm not very good at regex, is there any caveat?

**Comment by lucax88x** [comment]
Sorry @ZYinMD I really had some troubles this time, I'm moving to new house.. did fixing the regex like you said fixed your issue??

**Comment by ZYinMD** [comment]
Yes, it did fix my issue. I changed the regex to `[ ,-.{_("'<\[\t]`.

After the change, it's been working well for me so far, didn't find unexpected effects.

**Comment by lucax88x** [comment]
great, thanks! I'll document this in the readme!

**Comment by ZYinMD** [comment]
Maybe change the default regex too? In a way that doesn't affect existing users.

**Comment by lucax88x** [comment]
Yeah, I'll do that.

**Comment by lucax88x** [comment]
Released.
