### ISSUE TITLE
Jumping to "]" sign doesn't work

### ISSUE THREAD

**Issue by andsmi97** [lucax88x/CodeAceJumper#34]
I'm getting "No matches" message every time.

VSCode 1.36.1
Extension 2.1.5

**Comment by lucax88x** [comment]
I just tried and it's working fine, can you give me some more details?

**Comment by andsmi97** [comment]
I don't really know what can be useful so I'll give as much info as i can. So my enviroment is this:

Keybindings: 
```
[
  {
    "key": "ctrl+;",
    "command": "extension.aceJump"
  }
]
```

Settings

```
{
   "terminal.external.windowsExec": "C:\\Windows\\System32\\bash.exe",
   "terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
   "editor.fontSize": 16,
   "editor.tabSize": 2,
   "eslint.autoFixOnSave": true,
   "files.autoSave": "onFocusChange",
   "editor.minimap.enabled": false,
   "[javascript]": {
     "editor.defaultFormatter": "esbenp.prettier-vscode"
   },
   "[jsonc]": {
     "editor.defaultFormatter": "esbenp.prettier-vscode"
   },
   "workbench.settings.enableNaturalLanguageSearch": false,
   "window.zoomLevel": 0,
   "[typescript]": {
     "editor.defaultFormatter": "esbenp.prettier-vscode"
   },
   "[typescriptreact]": {
     "editor.defaultFormatter": "esbenp.prettier-vscode"
   },
   "editor.formatOnSave": true,
   "aceJump.finder.onlyInitialLetter": false,
   "emmet.includeLanguages": {
     "javascript": "css"
   }
 }
```

List of extensions:
Code Ace Jumper
Debugger for Chrome
Docker
GitLens
Prettier
Remote Development
Styled-Components

2 Keyboard layouts: English(qwerty) and Russian. I checked on English

Let me know if I can send something else

**Comment by lucax88x** [comment]
It's the only character that is not working? is jumping to [ working? normal letters?

**Comment by andsmi97** [comment]
I just checked, I got "Cancelled" message on "\\"(edited, it's backslash) sign sign and strange behavior on "^" sign which highlight every letter on screen. Rest works fine, including "[" sign

**Comment by ColCh** [comment]
Not works for me for this example

```
const foo = () => {
    return [];
}
```

try to jump on `]`

any other info? how to debug - are there any logs in extension?

**Comment by lucax88x** [comment]
@ColCh Sorry, I totally missed your comment :/

I'll do some tests during the week, you can debug by forking the repo and just pressing F5 in vscode, AFAIK I'm not adding any log, for now.

**Comment by pe224** [comment]
I noticed this as well when trying to resolve #150.
A sample code (in Python) would be
```python
a1 = []
a2 = f"This is a {[a1]}"
```
It is impossible to jump to the `]` after `a1`.
It *is* possible to jump to both `[`, though.
I tried a simple fix by adding `\\]` to the `finder.pattern`, but it didn't work - don't know why.
