### ISSUE TITLE
extension.aceJump.selection documentation seems to be wrong

### ISSUE THREAD

**Issue by LGala** [lucax88x/CodeAceJumper#440]
As you can see in the README file 

> - `extension.aceJump.multiChar` allows us to refine the placeholders by providing more characters. When one matches it automatically jumps, otherwise you can escape and then jump by matching remaining placeholders.

and

> - `extension.aceJump.selection` allows us to refine the placeholders by providing more characters. When one matches it automatically jumps, otherwise you can escape and then jump by matching remaining placeholders.

Are we sure this is correct?

**Comment by lucax88x** [comment]
it's possible that the only difference is that selection will select the text, but in the end the behavior is the same?

**Comment by LGala** [comment]
Yeah, this seems exactly what it does and I thought it would need a different description in order to help the users understand it
