### ISSUE TITLE
Help me to understand some settings!

### ISSUE THREAD

**Issue by LGala** [lucax88x/CodeAceJumper#441]
Ehi @lucax88x as a [first task](https://github.com/LGala/CodeAceJumper/tree/enhance-documentation#readme) I want to enhance the documentation but I don't understand some CodeAceJumper settings:
- "aceJump.placeholder.border"
- "aceJump.placeholder.fontWeight"
- "aceJump.highlight.backgroundColor"
- "aceJump.finder.includeEndCharInSelection"
- "aceJump.finder.jumpToLineEndings"

**Comment by lucax88x** [comment]
https://media.tenor.com/YJ3WjJVBjIQAAAAC/gandalf-i-have-no-memory-of-this-place.gif

Jokes aside..

from what I can see from the code looks like:

placeholder are settings of the placeholder, the box with the letter.

I actually don't remember what highlight is.. probably some operation to be done done after the placeholder one.

includeEndCharInSelection just includes the searched char... so the selection would select the whole or until the letter before, like in vim you use **f** o **b** if you want to include the letter.

jumpToLineEndings, I think this is specific for the jump to line, that mode used to print a placeholder on both lhe line and to also add a placeholder for the end of line (so you can jump start or end of line).

**Comment by LGala** [comment]
Thanks @lucax88x, besides the `jumpToLineEndings` I still don't see any behaviour changes when I add the other settings.

Maybe some of these don't work anymore because vscode got a lot of updates in the past 3/4 years?

I was was wondering: you'll feel ok if I create a new extension heavily inspired from yours? There are a lot of good work in this extension that can be theoretically reused but with all this legacy code and legacy dependencies it will be more difficult to maintain than not rewrite it from scratch, for my taste.

At the end of the day all the solved problems in this project can be reused and so I just need to rewrite it in a more modern way. Obviously I'll give you the credit for all the work you did.

Since this extension is used by several users i'd like to maintain the user base and "public Image" and give the users the idea that this new extension is the 2.0 version of CodeAceJumper, and so for me it could be wise to call it CodeAceJumper2, if you are ok.

**Comment by lucax88x** [comment]
You have my permission to do so :)

I would be just happy if you just add a link to my repo for the inspiration.

**Comment by LGala** [comment]
Of course, I'll do that!

**Comment by davecarrijo** [comment]
There´s a way to add a solid border around and padding?
