### ISSUE TITLE
feature request: search all open panes

### ISSUE THREAD

**Issue by geddski** [lucax88x/CodeAceJumper#7]
would be nice to be able to jump to any open & visible editing pane.

**Comment by lucax88x** [comment]
@geddski can you provide a better description of what you want?

Is this "workflow" something similar you wanted?
- you have 3 opened tabs
- you start an AceJump, and you type A
- we pop placeholders in all 3 tabs (each tab is starting A-Z)
- when you press the letter where you want to go, the current opened tab will be the winner

**Comment by geddski** [comment]
close! except I imagine the letter you press could take you to any tab, regardless of which tab is the current one. This way you could jump to other visible files quickly.

**Comment by lucax88x** [comment]
Ok, but if you want to see a "letter" in a tab, you need to switch to this tab, so the feature about jumping to chosen tab is quite "useless", as you already did it yourself, right?

What I can do, is to add a settings that, once enabled, can permit to have letters in all the opened tabs, but,

you can have a maximum of 26 \* 26 letters (676).

Could this satisfy you?
